### PR TITLE
Allow find medical information

### PR DESCRIPTION
**Pull request by sibinhho99-nus**
See [117](https://github.com/AY2122S2-CS2103T-T11-1/tp/issues/117)

### CODE REVIEW

**Comment by cheekean5848** [comment]
Can you explain to me what you are changing here

**Comment by sibinhho99-nus** [comment]
> Can you explain to me what you are changing here

Currently Joey disabled `find` for Medical screen because Clement previously thought there is always 1 medical record per patient. But this does not take into account that `view t/medical`, without NRIC specified, lists all available medical records. When you type `view t/medical` followed by `find` in the current version, you get this mismatch between the error message and what is displayed (there are multiple medical information records).

161258604-ddaea786-62f6-4491-9d47-97e6468a5121
`

**Comment by sibinhho99-nus** [comment]
> > Can you explain to me what you are changing here
> 
> Currently Joey disabled `find` for Medical screen because Clement previously thought there is always 1 medical record per patient. But this does not take into account that `view t/medical`, without NRIC specified, lists all available medical records. When you type `view t/medical` followed by `find` in the current version, you get this mismatch between the error message and what is displayed (there are multiple medical information records).
> 
> 161258604-ddaea786-62f6-4491-9d47-97e6468a5121 `

I'm bringing back the `find` command so that the user can search through the list of medical records

**Comment by sibinhho99-nus** [comment]
> I think find without NRIC is more like a global centric instead like a patient centric, doctor are focusing on patient centric right

Hmm but for any large list, I feel it's quite natural to want to search through/ filter them? Say a doctor might want to find all past patients with certain conditions and see what treatments worked for them

**Comment by cheekean5848** [comment]
We are not allowed to add in new features, how about we stick to the current one without viewing globally

**Comment by sibinhho99-nus** [comment]
> We are not allowed to add in new features, how about we stick to the current one without viewing globally

Ok, we cut then to be safe (cutting is allowed)? Need to i) make error message accurate ii) update UG, since medical information is listed there

Screenshot 2022-04-02 at 8 41 59 AM

**Comment by sibinhho99-nus** [comment]
@joey-chance

**Pull request closed without merging**
