### PR TITLE
Fix delete last entry bug

### PR DESCRIPTION
**Pull request by cheekean5848**

### CODE REVIEW

**Review by sibinhho99-nus — APPROVED** [review]
Hmm I think @clement0010 makes it return to Patients screen after deletion for contacts. I think either should be fine, but it might be better to standardize?

**Comment by cheekean5848** [comment]
I am doing the same thing, I just change the delete medical and conusltation back to patient once the last entry is removed

**Comment by sibinhho99-nus** [comment]
> Hmm I think @clement0010 makes it return to Patients screen after deletion for contacts. I think either should be fine, but it might be better to standardize?

I think showing the last list makes more sense
 

> I am doing the same thing, I just change the delete medical and conusltation back to patient once the last entry is removed

Ok, got it. Sounds good

**Comment by sibinhho99-nus** [comment]
> Ok, got it. Sounds good

**Pull request merged**
