### PR TITLE
Fix test result to string issue in json

### PR DESCRIPTION
**Pull request by joey-chance**

### CODE REVIEW

**Review by juslam19 — COMMENTED** [review]
I don't really see what this is supposed to do. I am making a separate PR that will solve the regression issue.

**Comment by joey-chance** [comment]
The regression issue is caused by the change in toString() method. This caused the data to be inputted in the json file to be of the wrong format, causing the issue of losing all data when the app is closed and reopened. These changes are to fix this regression issue by having another toDefaultString() method which will be called when making the json file.

**Comment by joey-chance** [comment]
> > The regression issue is caused by the change in toString() method. This caused the data to be inputted in the json file to be of the wrong format, causing the issue of losing all data when the app is closed and reopened. These changes are to fix this regression issue by having another toDefaultString() method which will be called when making the json file.
> 
> I believe the issue stems from the toString() function saving the date in the wrong format in the json file. See my PR for details.

Ya exactly why I used the different methods. Can you just run it with these changes before you say it doesn’t fix the issue? It works for me and Chee Kean too

**Comment by juslam19** [comment]
It does not appear to work for me. Hence I raised issue with this PR. Apologies.

**Comment by joey-chance** [comment]
> It does not appear to work for me. Hence I raised issue with this PR. Apologies.

Your code is doing the same thing in a different way. I don't see why mine doesn't work for you if urs does.

**Comment by juslam19** [comment]
> > It does not appear to work for me. Hence I raised issue with this PR. Apologies.
> 
> Your code is doing the same thing in a different way. I don't see why mine doesn't work for you if urs does.

Fair enough

**Review by juslam19 — APPROVED** [review]

**Pull request merged**
